# mi-chart/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mi.fullname" . }}
  labels:
    {{- include "mi.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "mi.fullname" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "mi.fullname" . }}
        {{- include "mi.labels" . | nindent 8 }}
    spec:
      containers:
        - name: contenedor-frontend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.containerPort }}
          envFrom:
            - configMapRef:
                name: {{ .Values.envFrom.configMap.name }}
            - secretRef:
                name: {{ .Values.envFrom.secret.name }}
          {{- if .Values.probes.startup.enabled }}
          startupProbe:
            httpGet:
              path: {{ .Values.probes.startup.path }}
              port: {{ .Values.containerPort }}
            failureThreshold: {{ .Values.probes.startup.failureThreshold }}
            periodSeconds: {{ .Values.probes.startup.periodSeconds }}
          {{- end }}
          readinessProbe:
            httpGet:
              path: {{ .Values.probes.readiness.path }}
              port: {{ .Values.containerPort }}
            failureThreshold: {{ .Values.probes.readiness.failureThreshold }}
            initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.readiness.periodSeconds }}
          livenessProbe:
            httpGet:
              path: {{ .Values.probes.liveness.path }}
              port: {{ .Values.containerPort }}
            failureThreshold: {{ .Values.probes.liveness.failureThreshold }}
            initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.liveness.periodSeconds }}
          {{- if and .Values.pvc.enabled .Values.pvc.mount.enabled }}
          volumeMounts:
            - name: datos
              mountPath: {{ .Values.pvc.mount.mountPath }}
          {{- end }}
      {{- if and .Values.pvc.enabled .Values.pvc.mount.enabled }}
      volumes:
        - name: datos
          persistentVolumeClaim:
            claimName: {{ .Values.pvc.name }}
      {{- end }}
