apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.names.service }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.labels.app }}
  ports:
    - protocol: TCP
      port: {{ .Values.servicePort }}
      targetPort: {{ .Values.containerPort }}
  type: ClusterIP
