# mi-chart/templates/configmap.yaml
{{- if .Values.envFrom.configMap.create }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.envFrom.configMap.name }}
  labels:
    {{- include "mi.labels" . | nindent 4 }}
data:
  {{- range $k, $v := .Values.envFrom.configMap.data }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
{{- end }}
