apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.names.deployment }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.labels.app }}
    areanegocio: {{ .Values.labels.areanegocio }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.labels.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.labels.app }}
    spec:
      containers:
        - name: frontend-container
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default "latest" }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.containerPort }}
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu | quote }}
              memory: {{ .Values.resources.requests.memory | quote }}
            limits:
              cpu: {{ .Values.resources.limits.cpu | quote }}
              memory: {{ .Values.resources.limits.memory | quote }}
          envFrom:
            - configMapRef:
                name: {{ .Values.names.configmap }}
          livenessProbe:
            tcpSocket:
              port: {{ .Values.probes.liveness.port }}
            failureThreshold: {{ .Values.probes.liveness.failureThreshold }}
            initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.liveness.periodSeconds }}
          readinessProbe:
            tcpSocket:
              port: {{ .Values.probes.readiness.port }}
            failureThreshold: {{ .Values.probes.readiness.failureThreshold }}
            initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.readiness.periodSeconds }}